name: CI/CD Pipeline

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build-test-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        id: build
        run: |
          & "C:\Program Files\Docker\Docker\resources\bin\docker.exe" exec springboot-web bash -c "cd /app && git pull && mvn package -DskipTests -Dmaven.compiler.enablePreview=true"

      - name: Test
        id: test
        run: |
          & "C:\Program Files\Docker\Docker\resources\bin\docker.exe" exec `
            -e SPRING_DATASOURCE_URL="jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=MySQL" `
            -e SPRING_DATASOURCE_DRIVER_CLASS_NAME="org.h2.Driver" `
            -e SPRING_DATASOURCE_USERNAME="root" `
            -e SPRING_DATASOURCE_PASSWORD="1234" `
            -e SPRING_JPA_DATABASE_PLATFORM="org.hibernate.dialect.H2Dialect" `
            springboot-web bash -c "cd /app && mvn test -Dspring.profiles.active=test -Dmaven.compiler.enablePreview=true"
        continue-on-error: true

      - name: Deploy with Ansible
        run: |
          & "C:\Program Files\Docker\Docker\resources\bin\docker.exe" exec springboot-web bash -c "cd /app && git pull && mvn package -DskipTests -Dmaven.compiler.enablePreview=true && mysqldump -h db -u root -pHello@123 --single-transaction B-KUOCH_Chyhang-db > /tmp/backup.sql && echo Deploy done"

      - name: Notify success
        run: echo "Build, test, and deployment completed successfully."

  notify-failure:
    runs-on: self-hosted
    needs: build-test-deploy
    if: failure()

    steps:
      - name: Send failure email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "BUILD FAILED: ${{ github.repository }} - ${{ github.sha }}"
          to: srengty@gmail.com,jihongkouch3@gmail.com
          from: ${{ secrets.MAIL_USERNAME }}
          body: |
            Build failed for repository: ${{ github.repository }}
            Branch: ${{ github.ref_name }}
            Committed by: ${{ github.actor }}
            Commit: ${{ github.sha }}
            Commit message: ${{ github.event.head_commit.message }}

            View the run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
